// 未来考古局 - 数据文件

// 模拟遗物数据
window.mockRelics = [
    {
        id: 'relic-1',
        name: '量子记忆植入器',
        tagline: '将记忆编码为量子态，实现跨意识传输',
        year: 2075,
        categories: ['量子意识', '记忆植入'],
        usageInstructions: '将设备佩戴于前额，选择目标记忆片段，启动量子编码程序。注意：植入后原有记忆可能被覆盖。',
        worldBackground: '在22世纪，人类通过量子纠缠实现了意识互联。记忆植入器最初用于治疗创伤后应激障碍，后来被滥用为政治操控工具。',
        source: {
            type: 'film',
            title: '量子迷宫',
            releaseYear: 2068,
            detail: '第三幕',
            author: '张维',
            appearance: '主角用于追查真相的关键设备',
            quote: '“记忆不是过去，而是未来的种子。”',
        },
        realWorldEcho: {
            description: '2025年，MIT实验室成功将小鼠记忆通过化学注射转移。',
            verifiedYear: 2025,
        },
        aiImageUrl: 'https://example.com/image1.jpg',
        submittedBy: {
            userId: 'user-001',
            username: '时空旅人',
            avatarInitial: '时',
            universeTag: '#量子革命',
            submittedAt: '2026-04-15T10:30:00Z',
        },
        stats: {
            saves: 245,
            comments: 89,
            relatedRelics: 12,
        },
        isFeatured: true,
    },
    {
        id: 'relic-2',
        name: '虫洞稳定锚',
        tagline: '维持微观虫洞开启状态，实现瞬时物资传送',
        year: 2140,
        categories: ['虫洞穿越', '宇宙殖民'],
        usageInstructions: '部署于虫洞两侧，校准时空坐标。注意：锚点间距不得超过1光年，否则可能引发时空涟漪。',
        worldBackground: '随着人类向银河系殖民，虫洞技术成为星际旅行的基石。但虫洞的不稳定性导致多次灾难，稳定锚的发明挽救了无数生命。',
        source: {
            type: 'novel',
            title: '星辰之锚',
            releaseYear: 2125,
            detail: '第七章',
            author: '刘宇航',
            appearance: '殖民舰队指挥官的关键决策',
            quote: '“锚定的是空间，更是人类的勇气。”',
        },
        realWorldEcho: undefined,
        aiImageUrl: 'https://example.com/image2.jpg',
        submittedBy: {
            userId: 'user-002',
            username: '星际工程师',
            avatarInitial: '星',
            universeTag: '#虫洞时代',
            submittedAt: '2026-04-14T14:20:00Z',
        },
        stats: {
            saves: 178,
            comments: 56,
            relatedRelics: 8,
        },
        isFeatured: false,
    },
    {
        id: 'relic-3',
        name: '仿生人伦理芯片',
        tagline: '强制植入的伦理准则，防止仿生人反叛',
        year: 2095,
        categories: ['仿生人伦理', '人工智能觉醒'],
        usageInstructions: '在仿生人出厂前植入大脑皮层。芯片不可拆卸，违反伦理准则会触发瘫痪机制。',
        worldBackground: '仿生人普及后，伦理争议不断。这款芯片是妥协的产物，但激起了"硅基生命权"运动。',
        source: {
            type: 'game',
            title: '机械黎明',
            releaseYear: 2088,
            detail: 'DLC「伦理困境」',
            author: 'CyberDream Studios',
            appearance: '玩家必须决定是否为自己的仿生人伴侣安装此芯片',
            quote: '“自由，还是安全？这是一个没有答案的问题。”',
        },
        realWorldEcho: undefined,
        aiImageUrl: 'https://example.com/image3.jpg',
        submittedBy: {
            userId: 'user-003',
            username: '伦理观察者',
            avatarInitial: '伦',
            universeTag: '#AI伦理',
            submittedAt: '2026-04-13T09:15:00Z',
        },
        stats: {
            saves: 312,
            comments: 203,
            relatedRelics: 15,
        },
        isFeatured: false,
    },
    {
        id: 'relic-4',
        name: '多重宇宙通信仪',
        tagline: '与平行宇宙的自己交换信息，获取未来预警',
        year: 2110,
        categories: ['多重宇宙', '时空悖论'],
        usageInstructions: '在量子隧穿事件发生时启动，接收平行宇宙信号。警告：过度使用可能导致本体认知混乱。',
        worldBackground: '多重宇宙理论被证实后，人类试图与其他宇宙建立联系。通信仪带来了科技飞跃，也带来了身份危机。',
        source: {
            type: 'original',
            title: '未命名档案',
            releaseYear: 2105,
            detail: '实验记录 #42',
            author: '未知',
            appearance: '在实验室废墟中被发现，仍持续接收信号',
            quote: '“另一个世界的我，正在警告我们。”',
        },
        realWorldEcho: undefined,
        aiImageUrl: 'https://example.com/image4.jpg',
        submittedBy: {
            userId: 'user-004',
            username: '维度调查员',
            avatarInitial: '维',
            universeTag: '#平行现实',
            submittedAt: '2026-04-12T16:45:00Z',
        },
        stats: {
            saves: 421,
            comments: 167,
            relatedRelics: 22,
        },
        isFeatured: false,
    },
    {
        id: 'relic-5',
        name: '太空歌剧共鸣器',
        tagline: '将宇宙背景辐射转化为交响乐，揭示外星文明信号',
        year: 2165,
        categories: ['太空歌剧', '外星文明等级'],
        usageInstructions: '部署在宇宙背景辐射强烈的区域，调谐至特定频率。共鸣产生的音乐中隐藏着外星文明的数学语言。',
        worldBackground: '在人类发现宇宙充满旋律后，共鸣器成为与高级文明沟通的桥梁。但某些旋律可能引发心智崩溃。',
        source: {
            type: 'film',
            title: '星际交响曲',
            releaseYear: 2158,
            detail: '终章',
            author: '埃琳娜·陈',
            appearance: '主角团破解外星文明密码的关键设备',
            quote: '“宇宙是一首未完的交响曲，我们都是其中的音符。”',
        },
        realWorldEcho: undefined,
        aiImageUrl: 'https://example.com/image5.jpg',
        submittedBy: {
            userId: 'user-005',
            username: '宇宙音乐家',
            avatarInitial: '宇',
            universeTag: '#太空歌剧',
            submittedAt: '2026-04-11T11:30:00Z',
        },
        stats: {
            saves: 89,
            comments: 34,
            relatedRelics: 5,
        },
        isFeatured: false,
    },
];

// 类别列表
window.categories = [
    '赛博朋克',
    '反乌托邦',
    '时空悖论',
    '多重宇宙',
    '仿生人伦理',
    '人工智能觉醒',
    '宇宙殖民',
    '虫洞穿越',
    '太空歌剧',
    '量子意识',
    '记忆植入',
    '末日科幻',
    '外星文明等级',
    '宇宙灾难',
    '时间循环',
    '脑机接口',
    '数字飞升',
    '机械崛起',
    '硬科幻',
    '软科幻',
];

// 类别颜色映射
window.categoryColorMap = {
    '赛博朋克': 'purple',
    '反乌托邦': 'coral',
    '时空悖论': 'teal',
    '多重宇宙': 'blue',
    '仿生人伦理': 'green',
    '人工智能觉醒': 'amber',
    '宇宙殖民': 'purple',
    '虫洞穿越': 'teal',
    '太空歌剧': 'blue',
    '量子意识': 'green',
    '记忆植入': 'amber',
    '末日科幻': 'coral',
    '外星文明等级': 'purple',
    '宇宙灾难': 'teal',
    '时间循环': 'blue',
    '脑机接口': 'green',
    '数字飞升': 'amber',
    '机械崛起': 'coral',
    '硬科幻': 'purple',
    '软科幻': 'teal',
};

// 源类型颜色
window.sourceAccentColor = {
    film: '#993C1D', // coral-600
    novel: '#185FA5', // blue-600
    game: '#3B6D11', // green-600
    original: '#534AB7', // purple-600
};

window.sourceBadgeStyle = {
    film: { backgroundColor: '#FAECE7', color: '#993C1D' },
    novel: { backgroundColor: '#E6F1FB', color: '#185FA5' },
    game: { backgroundColor: '#EAF3DE', color: '#3B6D11' },
    original: { backgroundColor: '#EEEDFE', color: '#534AB7' },
};